<?php



    // List of allowed robots.
    // (case insensitive)
    //
    // Format: ,"robot_name"
    // (comma and double quotes are mandatory)
    //

    $allowed_robots = array(
	    "googlebot"
	    ,"bingbot"

    );
    // End list


    // List of NOT allowed robots.
    // (case insensitive)
    //
    // Format: ,"robot_name"
    // (comma and double quotes are mandatory)
    //

    $not_allowed_robots = array(
	    "Baiduspider"
	    ,"MJ12bot"
	    ,"AhrefsBot"
	    ,"Sogou web spider"
	    ,"YandexBot"
	    ,"360Spider"
	    ,"Ezooms"
	    ,"YoudaoBot"
	    ,"RU_Bot"
	    ,"BLEXBot"
        ,"slurp"
	    ,"msnbot"
	    ,"UptimeRobot"
	    ,"wget"

    ,"ABCdatos"
    ,"Acme"
    ,"Ahoy"
    ,"Alkaline"
    ,"Anthill"
    ,"Walhello appie"
    ,"Arachnophilia"
    ,"Arale"
    ,"Araneo"
    ,"AraybOt"
    ,"ArchitextSpider"
    ,"Aretha"
    ,"ARIADNE"
    ,"arks"
    ,"AskJeeves"
    ,"ASpider"
    ,"ATN Worldwide"
    ,"Atomz"
    ,"AURESYS"
    ,"BackRub"
    ,"Bay Spider"
    ,"Big Brother"
    ,"Bjaaland"
    ,"BlackWidow"
    ,"Die Blinde Kuh"
    ,"Bloodhound"
    ,"Borg-Bot"
    ,"BoxSeaBot"
    ,"bright.net"
    ,"BSpider"
    ,"CACTVS"
    ,"Calif"
    ,"Cassandra"
    ,"Digimarc"
    ,"Checkbot"
    ,"ChristCrawler.com"
    ,"churl"
    ,"cIeNcIaFiCcIoN.nEt"
    ,"CMC"
    ,"Collective"
    ,"Combine System"
    ,"Conceptbot"
    ,"ConfuzzledBot"
    ,"CoolBot"
    ,"Web Core / Roots"
    ,"XYLEME Robot"
    ,"Internet Cruiser Robot"
    ,"Cusco"
    ,"CyberSpyder Link Test"
    ,"CydralSpider"
    ,"Desert Realm Spider"
    ,"DeWeb"
    ,"DienstSpider"
    ,"Digger"
    ,"Digital Integrity Robot"
    ,"Direct Hit Grabber"
    ,"DNAbot"
    ,"DownLoad Express"
    ,"DragonBot"
    ,"DWCP"
    ,"e-collector"
    ,"EbiNess"
    ,"EIT Link Verifier Robot"
    ,"ELFINBOT"
    ,"Emacs-w3 Search Engine"
    ,"ananzi"
    ,"esculapio"
    ,"Esther"
    ,"Evliya Celebi"
    ,"FastCrawler"
    ,"Fluid Dynamics Search Engine robot"
    ,"Felix IDE"
    ,"Wild Ferret Web Hopper"
    ,"FetchRover"
    ,"fido"
    ,"Hämähäkki"
    ,"KIT-Fireball"
    ,"Fish search"
    ,"Fouineur"
    ,"Robot Francoroute"
    ,"Freecrawl"
    ,"FunnelWeb"
    ,"gammaSpider"
    ,"FocusedCrawler"
    ,"gazz"
    ,"GCreep"
    ,"GetBot"
    ,"GetURL"
    ,"Golem"
    ,"Grapnel"
    ,"Griffon"
    ,"Gromit"
    ,"Northern Light Gulliver"
    ,"Gulper Bot"
    ,"HamBot"
    ,"Harvest"
    ,"havIndex"
    ,"HI (HTML Index) Search"
    ,"Hometown Spider Pro"
    ,"ht://Dig"
    ,"HTMLgobble"
    ,"Hyper-Decontextualizer"
    ,"iajaBot"
    ,"IBM_Planetwide"
    ,"Popular Iconoclast"
    ,"Ingrid"
    ,"Imagelock"
    ,"IncyWincy"
    ,"Informant"
    ,"InfoSeek"
    ,"Infoseek Sidewinder"
    ,"InfoSpiders"
    ,"Inspector Web"
    ,"IntelliAgent"
    ,"I, Robot"
    ,"Iron33"
    ,"Israeli-search"
    ,"JavaBee"
    ,"JBot Java Web Robot"
    ,"JCrawler"
    ,"Jeeves"
    ,"JoBo Java Web Robot"
    ,"Jobot"
    ,"JoeBot"
    ,"The Jubii Indexing Robot"
    ,"JumpStation"
    ,"image.kapsi.net"
    ,"Katipo"
    ,"KDD-Explorer"
    ,"Kilroy"
    ,"KO_Yappo_Robot"
    ,"LabelGrabber"
    ,"larbin"
    ,"legs"
    ,"Link Validator"
    ,"LinkScan"
    ,"LinkWalker"
    ,"Lockon"
    ,"logo.gif Crawler"
    ,"Lycos"
    ,"WWWWorm"
    ,"Magpie"
    ,"marvin/infoseek"
    ,"Mattie"
    ,"MediaFox"
    ,"MerzScope"
    ,"NEC-MeshExplorer"
    ,"MindCrawler"
    ,"mnoGoSearch"
    ,"moget"
    ,"MOMspider"
    ,"Monster"
    ,"Motor"
    ,"Muncher"
    ,"Muninn"
    ,"Muscat Ferret"
    ,"Mwd.Search"
    ,"Internet Shinchakubin"
    ,"NDSpider"
    ,"Nederland.zoek"
    ,"NetCarta WebMap Engine"
    ,"NetMechanic"
    ,"NetScoop"
    ,"newscan-online"
    ,"NHSE Web Forager"
    ,"Nomad"
    ,"The NorthStar Robot"
    ,"nzexplorer"
    ,"ObjectsSearch"
    ,"Occam"
    ,"HKU WWW Octopus"
    ,"OntoSpider"
    ,"Openfind data gatherer"
    ,"Orb Search"
    ,"Pack Rat"
    ,"PageBoy"
    ,"ParaSite"
    ,"Patric"
    ,"pegasus"
    ,"Peregrinator"
    ,"PerlCrawler"
    ,"Phantom"
    ,"PhpDig"
    ,"PiltdownMan"
    ,"Pimptrain.com"
    ,"Pioneer"
    ,"html_analyzer"
    ,"Portal Juice Spider"
    ,"PGP Key Agent"
    ,"PlumtreeWebAccessor"
    ,"Poppi"
    ,"PortalB Spider"
    ,"psbot"
    ,"GetterroboPlus Puu"
    ,"The Python Robot"
    ,"Raven Search"
    ,"RBSE Spider"
    ,"Resume Robot"
    ,"RoadHouse Crawling System"
    ,"RixBot"
    ,"Road Runner: The ImageScape Robot"
    ,"Robbie the Robot"
    ,"ComputingSite Robi"
    ,"RoboCrawl Spider"
    ,"RoboFox"
    ,"Robozilla"
    ,"Roverbot"
    ,"RuLeS"
    ,"SafetyNet Robot"
    ,"Scooter"
    ,"Sleek"
    ,"Search.Aus-AU.COM"
    ,"SearchProcess"
    ,"Senrigan"
    ,"SG-Scout"
    ,"ShagSeeker"
    ,"Shai'Hulud"
    ,"Sift"
    ,"Simmany Robot Ver"
    ,"Site Valet"
    ,"Open Text Index Robot"
    ,"SiteTech-Rover"
    ,"Skymob.com"
    ,"SLCrawler"
    ,"Inktomi Slurp"
    ,"Smart Spider"
    ,"Snooper"
    ,"Solbot"
    ,"Spanner"
    ,"Speedy Spider"
    ,"spider_monkey"
    ,"SpiderBot"
    ,"Spiderline Crawler"
    ,"SpiderMan"
    ,"SpiderView"
    ,"Spry Wizard Robot"
    ,"Site Searcher"
    ,"Suke"
    ,"suntek search engine"
    ,"Sven"
    ,"Sygol"
    ,"TACH Black Widow"
    ,"Tarantula"
    ,"tarspider"
    ,"Tcl W3 Robot"
    ,"TechBOT"
    ,"Templeton"
    ,"TeomaTechnologies"
    ,"TITAN"
    ,"TitIn"
    ,"The TkWWW Robot"
    ,"TLSpider"
    ,"UCSD Crawl"
    ,"UdmSearch"
    ,"UptimeBot"
    ,"URL Check"
    ,"URL Spider Pro"
    ,"Valkyrie"
    ,"Verticrawl"
    ,"Victoria"
    ,"vision-search"
    ,"void-bot"
    ,"Voyager"
    ,"VWbot"
    ,"The NWI Robot"
    ,"W3M2"
    ,"WallPaper"
    ,"the World Wide Web Wanderer"
    ,"w@pSpider by wap4.com"
    ,"WebBandit Web Spider"
    ,"WebCatcher"
    ,"WebCopy"
    ,"webfetcher"
    ,"The Webfoot Robot"
    ,"Webinator"
    ,"weblayers"
    ,"WebLinker"
    ,"WebMirror"
    ,"The Web Moose"
    ,"WebQuest"
    ,"Digimarc MarcSpider"
    ,"WebReaper"
    ,"webs"
    ,"Websnarf"
    ,"WebSpider"
    ,"WebVac"
    ,"webwalk"
    ,"WebWalker"
    ,"WebWatch"
    ,"whatUseek Winona"
    ,"WhoWhere Robot"
    ,"Wired Digital"
    ,"Weblog Monitor"
    ,"w3mir"
    ,"WebStolperer"
    ,"The Web Wombat"
    ,"The World Wide Web Worm"
    ,"WWWC"
    ,"WebZinger"
    ,"XGET"
    );
    // End list



    // List of NOT allowed robot PATTERNS.
    // (case insensitive)
    //
    // Format: ,"robot_pattern"
    // (comma and double quotes are mandatory)
    //
    $not_allowed_robot_patterns = array(
	    "spider"
	    ,"bot"
	    ,"crawler"
	    ,"robot"
    );
